---
            all:
             children:
               web:
                 hosts:
                   web1:
                     ansible_host: 192.168.0.10
                   web2:
                     ansible_host: web2.example.com
               database:
                 hosts:
                   db1:
                     ansible_user: rhel
            
